CoreBridge/Controllers/AppUserRegisterController.cs
using AutoMapper;
using CoreBridge.Models;
using CoreBridge.Models.DTO;
using CoreBridge.Models.Entity;
using CoreBridge.Models.lib;
using CoreBridge.Services;
using CoreBridge.Services.Interfaces;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Rewrite;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Text;
using System.Xml.Linq;
using System.Text.RegularExpressions;

namespace CoreBridge.Controllers
{

    public class AppUserRegisterController : Controller
    {
        private readonly IAppUserService _appUserService;
        private readonly ITitleInfoService _titleInfoService;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IUserStore<IdentityUser> _userStore;
        private readonly ILogger<UserLoginController> _logger;
        private readonly RoleManager<IdentityRole> _roleManager;

        public AppUserRegisterController(IAppUserService appUserSerice, ITitleInfoService titleInfoService, SignInManager<IdentityUser> signInManager,
            UserManager<IdentityUser> userManager, IUserStore<IdentityUser> userStore, ILogger<UserLoginController> logger, RoleManager<IdentityRole> roleManager)
        {
            _appUserService = appUserSerice;
            _titleInfoService = titleInfoService;
            _signInManager = signInManager;
            _userManager = userManager;
            _userStore = userStore;
            _logger = logger;
            _roleManager = roleManager;
        }

        public async Task<IActionResult> Index()
        {
            AppUserDto appUser = new();
            UserOperation userManager = new(_appUserService);

            appUser.UserId = await userManager.CreateUserId();
            if (appUser.UserId == String.Empty)
            {
                return View();
            }
            return View(appUser);
            //return View();
        }

        [HttpPost]
        public async Task<IActionResult> Confirm(AppUserDto dto)
        {
            ViewBag.Alert = null;

            //タイトルコードの存在は確認する.
            if (dto.TitleCode != null)
            {
                //タイトルコードの存在は確認する.
                var check = await _titleInfoService.FindTitleCode(dto.TitleCode);
                if (check == false)
                {
                    string errorMsg = "同一のタイトルコードがあませんでした！登録済みタイトルコードを利用してください。";
                    ViewBag.Alert = errorMsg;
                    ModelState.AddModelError(string.Empty, errorMsg);
                }
            }

            //パスワードの手動でのバリテーション
            if(dto.Password != null)
            {
                var hasNumber = new Regex(@"[0-9]+");
                var hasUpperChar = new Regex(@"[A-Z]+");
                var hasMinimum8Chars = new Regex(@".{8,}");
                var hasOtherChar= new Regex(@"[^a-zA-Z0-9]+");

                var isValidated = hasNumber.IsMatch(dto.Password) && hasUpperChar.IsMatch(dto.Password)
                    && hasMinimum8Chars.IsMatch(dto.Password) && hasOtherChar.IsMatch(dto.Password);
                if (isValidated == false)
                {
                    //エラーにする
                    string errorMsg = "パスワードに使われている文字列が正しくありません！8文字以上の大文字・小文字・数値・数値以外の値が入ったパスワードを使用してください";
                    ViewBag.Alert = errorMsg;

                    ModelState.AddModelError(string.Empty, errorMsg);
                }
            }

            if (dto.Password != dto.ConfirmPassword)
            {
                //エラーメッセージ
                string errorMsg = "パスワードが一致しませんでした。一致するパスワードを使用してください";
                ViewBag.Alert = errorMsg;

                ModelState.AddModelError(string.Empty, errorMsg);
            }

            var emailCheck = await _userManager.FindByEmailAsync(dto.Email);
            if (emailCheck != null)
            {
                string errorMsg = "登録済みのEmailアドレスです。未登録のEmailを利用してください。";
                ViewBag.Alert = errorMsg;
                ModelState.AddModelError(string.Empty, errorMsg);
            }

            return View(dto);
        }

        [HttpPost]
        public async Task<IActionResult> Create(AppUserDto dto)
        {
            string returnUrl = Url.Content("~/AppUserRegister");

            if (ModelState.IsValid)
            {
                var user = CreateUser();
                await _userStore.SetUserNameAsync(user, dto.UserId, CancellationToken.None);

                var result = await _userManager.CreateAsync(user, dto.Password);
                if (result.Succeeded)
                {
                    _logger.LogInformation("User created a new account with password.");

                    var userId = await _userManager.GetUserIdAsync(user);
                    var userEmail = await _userManager.SetEmailAsync(user, dto.Email);
                    var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);

                    //ロール管理追加.
                    await CheckAppRole(dto.Role.ToString());
                    var role = await _userManager.AddToRoleAsync(user, dto.Role.ToString());

                    //パスワードをハッシュ化
                    var passwordHash = _userManager.PasswordHasher.HashPassword(user, dto.Password);
                    dto.Password = passwordHash;

                    //DB登録
                    await _appUserService.GenerateAppUser(dto);
                    return View(dto);
                }

                ViewBag.Alert = "登録に失敗しました";
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }

            return View(dto);
        }

        private IdentityUser CreateUser()
        {
            try
            {
                return Activator.CreateInstance<IdentityUser>();
            }
            catch
            {
                throw new InvalidOperationException($"Can't create an instance of '{nameof(IdentityUser)}'. " +
                    $"Ensure that '{nameof(IdentityUser)}' is not an abstract class and has a parameterless constructor, or alternatively " +
                    $"override the register page in /Areas/Identity/Pages/Account/Register.cshtml");
            }
        }

        /// <summary>
        /// ロール管理
        /// </summary>
        private async Task CheckAppRole(string roleName)
        {
            IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(roleName));
            if (result.Succeeded)
            {
                //成功
            }
        }

    }
}

CoreBridge/Views/AppUserRegister/Confirm.cshtml
@model CoreBridge.Models.DTO.AppUserDto
@{
    Layout = "_TopLayout";
}
<div class="w-full flex flex-wrap">
    <!-- Register Section -->
    <div class="w-full md:w-1/2 flex flex-col">

        @Html.Partial("_logo")

        <div class="flex flex-col justify-center md:justify-start my-auto pt-8 md:pt-0 px-8 md:px-24 lg:px-32">
            <p class="text-center text-3xl">以下の内容で登録をしますか？</p>
            @Html.Partial("_FormError")
            <form class="flex flex-col pt-3 md:pt-8" asp-controller="AppUserRegister" asp-action="Create" method="post">
                @Html.AntiForgeryToken()
                <div class="flex flex-col pt-4">
                    <label for="userid" class="text-lg">User ID</label>
                    @Model.UserId
                    <input asp-for="@Model.UserId" type="hidden" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline" />
                </div>

                <div class="flex flex-col pt-4">
                    <label for="titel code" class="text-lg">Title Code</label>
                    @Model.TitleCode
                    <input asp-for="@Model.TitleCode" type="hidden" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline" />
                </div>

                <div class="flex flex-col pt-4">
                    <label for="titel code" class="text-lg">Role</label>
                    @Model.Role
                    <input asp-for="@Model.Role" type="hidden" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline" />
                </div>

                <div class="flex flex-col pt-4">
                    <label for="titel code" class="text-lg">Email</label>
                    @Model.Email
                    <input asp-for="@Model.Email" type="hidden" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline" />
                </div>

                <div class="flex flex-col pt-4">
                    <label for="password" class="text-lg">Password</label>
                    @Model.Password
                    <input asp-for="@Model.Password" type="hidden" placeholder="Password" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline" />
                </div>

                <div class="flex flex-col pt-4">
                    <label for="confirm-password" class="text-lg">Confirm Password</label>
                    @Model.ConfirmPassword
                    <input asp-for="@Model.ConfirmPassword" type="hidden" placeholder="Password" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline" />
                </div>
                @if (ViewBag.Alert == null)
                {
                    <input type="submit" value="Register" class="bg-black text-white font-bold text-lg hover:bg-gray-700 p-2 mt-8" />
                }
            </form>
            <div class="text-center pt-12 pb-12">
                <div>
                    <a asp-action="Index">前の画面に戻る</a>
                </div>
            </div>
        </div>

    </div>

    <!-- Image Section -->
    <div class="w-1/2 shadow-2xl">
        <img class="object-cover w-full h-screen hidden md:block" src="https://source.unsplash.com/IXUM4cJynP0" alt="Background" />
    </div>
</div>
<script>
    var alert_del = document.querySelectorAll('.alert-del');
    alert_del.forEach((x) =>
        x.addEventListener('click', function () {
            x.parentElement.classList.add('hidden');
        })
    );
</script>

CoreBridge/Views/AppUserRegister/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_TopLayout";
}
<div class="w-full flex flex-wrap">
    <!-- Register Section -->
    <div class="w-full md:w-1/2 flex flex-col">

        @*@Html.Partial("_logo")*@
        @Html.Partial("_FormError")
        @if (ViewBag.Alert == null){
            <div class="flex flex-col justify-center md:justify-start my-auto pt-8 md:pt-0 px-8 md:px-24 lg:px-32">
                <p class="text-center text-3xl">登録完了</p>
            </div>
        }else{
            <div class="flex flex-col justify-center md:justify-start my-auto pt-8 md:pt-0 px-8 md:px-24 lg:px-32">
                <p class="text-center text-3xl">登録が失敗しました</p>
            </div>
        }

        <p>一覧は<a href="/Accounts" class="underline font-semibold">こちら</a>から！</p>
    </div>
</div>

CoreBridge/Views/AppUserRegister/Index.cshtml
@model CoreBridge.Models.DTO.AppUserDto
@{
    Layout = "_TopLayout";
}

@if (ViewBag.Alert != null)
{
    <div class="flex justify-between text-red-200 shadow-inner rounded p-3 bg-red-600">
        <p class="self-center">@ViewBag.Alert</p>
        <strong class="text-xl align-center cursor-pointer alert-del">&times;</strong>
    </div>
}
<div class="w-full flex flex-wrap">
    <!-- Register Section -->
    <div class="w-full md:w-1/2 flex flex-col">

        @Html.Partial("_logo")

        <div class="flex flex-col justify-center md:justify-start my-auto pt-8 md:pt-0 px-8 md:px-24 lg:px-32">
            <p class="text-center text-3xl">ユーザー情報登録</p>
            @Html.Partial("_FormError")
            <form class="flex flex-col pt-3 md:pt-8" asp-controller="AppUserRegister" asp-action="Confirm" method="post">
                @Html.AntiForgeryToken()
                <div class="flex flex-col pt-4">
                    <label for="name" class="text-lg">User ID</label>
                    <input asp-for="@Model.UserId" type="text" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline" readonly/>
                </div>

                <div class="flex flex-col pt-4">
                    <label for="titlecode" class="text-lg">Title Code</label>
                    <input asp-for="@Model.TitleCode" type="text" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline" />
                </div>

                <div class="flex flex-col pt-4">
                    <label for="userrole" class="text-lg">User Role</label>
                    <select asp-for="@Model.Role" class="form-control" asp-items="Html.GetEnumSelectList<AdminUserRoleEnum>()"></select>
                </div>

                <div class="flex flex-col pt-4">
                    <label for="email" class="text-lg">Email</label>
                    <input asp-for="@Model.Email" type="email" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline" />
                </div>

                <div class="flex flex-col pt-4">
                    <label for="password" class="text-lg">Password</label>
                    <input asp-for="@Model.Password" type="password" placeholder="Password" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline" />
                </div>

                <div class="flex flex-col pt-4">
                    <label for="confirm-password" class="text-lg">Confirm Password</label>
                    <input asp-for="@Model.ConfirmPassword" type="password" placeholder="Password" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline" />
                </div>

                <input type="submit" value="Register" class="bg-black text-white font-bold text-lg hover:bg-gray-700 p-2 mt-8" />
            </form>
            <div class="text-center pt-12 pb-12">
                <p>Already have an account? <a href="/" class="underline font-semibold">Log in here.</a></p>
            </div>
        </div>

    </div>

    <!-- Image Section -->
    <div class="w-1/2 shadow-2xl">
        <img class="object-cover w-full h-screen hidden md:block" src="https://source.unsplash.com/IXUM4cJynP0" alt="Background" />
    </div>
</div>
<script>
    var alert_del = document.querySelectorAll('.alert-del');
    alert_del.forEach((x) =>
        x.addEventListener('click', function () {
            x.parentElement.classList.add('hidden');
        })
    );
</script>