CoreBridge/Controllers/UserRegisterController.cs
using CoreBridge.Models.DTO;
using CoreBridge.Services.Interfaces;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using System.Text;
using System.Text.Encodings.Web;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using CoreBridge.Models;
using XAct.Users;


namespace CoreBridge.Controllers
{
    public class UserRegisterController : Controller
    {
        private readonly IAdminUserService _adminUserService;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IUserStore<IdentityUser> _userStore;
        private readonly IUserEmailStore<IdentityUser> _emailStore;
        private readonly ILogger<UserRegisterController> _logger;
        private readonly IEmailSender _emailSender;

        public UserRegisterController(ILogger<UserRegisterController> logger, IAdminUserService adminUserService, UserManager<IdentityUser> userManager,
            SignInManager<IdentityUser> signInManager, RoleManager<IdentityRole> roleManager, IUserStore<IdentityUser> userStore, IEmailSender emailSender)
        {
            _logger = logger;
            _adminUserService = adminUserService;
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
            _userStore = userStore;
            _emailStore = GetEmailStore();
            _emailSender = emailSender;
        }

        public IActionResult Index()
        {
            return View();
        }

        public string ReturnUrl { get; set; }
        public IList<AuthenticationScheme> ExternalLogins { get; set; }
        public bool DisplayConfirmAccountLink { get; set; }
        public string EmailConfirmationUrl { get; set; }

        [HttpPost]
        public async Task<IActionResult> Confirm(AdminUserDto dto)
        {
            var user = await _userManager.FindByEmailAsync(dto.EMail);
            if (user != null)
            {
                ViewBag.Alert = "既に利用されているEmailアドレスです！";
                ModelState.AddModelError(string.Empty, "既に利用されているEmailアドレスです！");
                return View(dto);
            }

            if (dto.IsValid())
            {
                return View(dto);
            }
            else
            {
                return View("/");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Create(AdminUserDto dto)
        {
            string returnUrl = Url.Content("~/");

            if (ModelState.IsValid)
            {
                //サインインのための処理
                var user = CreateUser();

                await _userStore.SetUserNameAsync(user, dto.EMail, CancellationToken.None);
                await _emailStore.SetEmailAsync(user, dto.EMail, CancellationToken.None);

                var result = await _userManager.CreateAsync(user, dto.Password);
                if (result.Succeeded)
                {
                    _logger.LogInformation("User created a new account with password.");

                    var userId = await _userManager.GetUserIdAsync(user);
                    var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);

                    //ロール追加(強制的にAdminUserのみ)
                    await _roleManager.CreateAsync(new IdentityRole(AdminUserRoleEnum.AdminUser.ToString()));
                    await _userManager.AddToRoleAsync(user, AdminUserRoleEnum.AdminUser.ToString());

                    //Email設定
                    await _userManager.SetEmailAsync(user, dto.EMail);

                    //パスワードをハッシュ化
                    var passwordHash = _userManager.PasswordHasher.HashPassword(user, dto.Password);
                    dto.Password = passwordHash;

                    //DB登録
                    await _adminUserService.GenerateAdminUser(dto);

                    if (_userManager.Options.SignIn.RequireConfirmedAccount)
                    {
                        return RedirectToPage("RegisterConfirmation", new { email = dto.EMail, returnUrl = returnUrl });
                    }
                    else
                    {
                        await _signInManager.SignInAsync(user, isPersistent: false);
                        return LocalRedirect(returnUrl);
                    }
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }

            return View(dto);
        }

        private IdentityUser CreateUser()
        {
            try
            {
                return Activator.CreateInstance<IdentityUser>();
            }
            catch
            {
                throw new InvalidOperationException($"Can't create an instance of '{nameof(IdentityUser)}'. " +
                    $"Ensure that '{nameof(IdentityUser)}' is not an abstract class and has a parameterless constructor, or alternatively " +
                    $"override the register page in /Areas/Identity/Pages/Account/Register.cshtml");
            }
        }

        private IUserEmailStore<IdentityUser> GetEmailStore()
        {
            if (!_userManager.SupportsUserEmail)
            {
                throw new NotSupportedException("The default UI requires a user store with email support.");
            }
            return (IUserEmailStore<IdentityUser>)_userStore;
        }
    }
}

CoreBridge/Views/UserRegister/Confirm.cshtml
@model CoreBridge.Models.DTO.AdminUserDto
@{
    Layout = "_TopLayout";
}
<div class="w-full flex flex-wrap">
    <!-- Register Section -->
    <div class="w-full md:w-1/2 flex flex-col">

        @Html.Partial("_logo")
        
        <div class="flex flex-col justify-center md:justify-start my-auto pt-8 md:pt-0 px-8 md:px-24 lg:px-32">
            <p class="text-center text-3xl">以下の内容で登録をしますか？</p>
            @Html.Partial("_FormError")
            <form class="flex flex-col pt-3 md:pt-8" asp-controller="UserRegister" asp-action="Create" method="post" >
                @Html.AntiForgeryToken()
                <div class="flex flex-col pt-4">
                    <label for="name" class="text-lg">Name</label>
                    @Model.Name
                    <input asp-for="@Model.Name" type="hidden" placeholder="John Smith" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline"  />
                </div>

                <div class="flex flex-col pt-4">
                    <label for="email" class="text-lg">Email</label>
                    @Model.EMail
                    <input asp-for="@Model.EMail" type="hidden" placeholder="your@email.com" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline" />
                </div>

                <div class="flex flex-col pt-4">
                    <label for="password" class="text-lg">Password</label>
                    @Model.Password
                    <input asp-for="@Model.Password" type="hidden" placeholder="Password" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline" />
                </div>

                <div class="flex flex-col pt-4">
                    <label for="confirm-password" class="text-lg">Confirm Password</label>
                    @Model.ConfirmPassword
                    <input asp-for="@Model.ConfirmPassword" type="hidden" placeholder="Password" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline" />
                </div>
                @if (ViewBag.Alert == null)
                {
                    <input type="submit" value="Register" class="bg-black text-white font-bold text-lg hover:bg-gray-700 p-2 mt-8" />
                }
            </form>
            <div class="text-center pt-12 pb-12">
                <div>
                    <a asp-controller="UserRegister" asp-action="Index">前の画面に戻る</a>
                </div>
            </div>
        </div>

    </div>

    <!-- Image Section -->
    <div class="w-1/2 shadow-2xl">
        <img class="object-cover w-full h-screen hidden md:block" src="https://source.unsplash.com/IXUM4cJynP0" alt="Background" />
    </div>
</div>

CoreBridge/Views/UserRegister/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_TopLayout";
}
<div class="w-full flex flex-wrap">
    <!-- Register Section -->
    <div class="w-full md:w-1/2 flex flex-col">
        @*@Html.Partial("_logo")*@
        @Html.Partial("_FormError")
        @if (ViewBag.Alert == null)
        {
            <div class="flex flex-col justify-center md:justify-start my-auto pt-8 md:pt-0 px-8 md:px-24 lg:px-32">
                <p class="text-center text-3xl">登録完了</p>
            </div>
        }else{
            <div class="flex flex-col justify-center md:justify-start my-auto pt-8 md:pt-0 px-8 md:px-24 lg:px-32">
                <p class="text-center text-3xl">登録が失敗しました</p>
            </div>
        }
    </div>
</div>

CoreBridge/Views/UserRegister/Index.cshtml
@model CoreBridge.Models.DTO.AdminUserDto
@{
    Layout = "_TopLayout";
}
<div class="w-full flex flex-wrap">
    <!-- Register Section -->
    <div class="w-full md:w-1/2 flex flex-col">

        @Html.Partial("_logo")

        <div class="flex flex-col justify-center md:justify-start my-auto pt-8 md:pt-0 px-8 md:px-24 lg:px-32">
            <p class="text-center text-3xl">Join Us.</p>
            @Html.Partial("_FormError")
            <form class="flex flex-col pt-3 md:pt-8" asp-controller="UserRegister" asp-action="Confirm" method="post" >
                @Html.AntiForgeryToken()
                <div class="flex flex-col pt-4">
                    <label for="name" class="text-lg">Name</label>
                    <input asp-for="@Model.Name" type="text" placeholder="John Smith" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline"  />
                </div>

                <div class="flex flex-col pt-4">
                    <label for="email" class="text-lg">Email</label>
                    <input asp-for="@Model.EMail" type="email" placeholder="your@email.com" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline" />
                </div>

                <div class="flex flex-col pt-4">
                    <label for="password" class="text-lg">Password</label>
                    <input asp-for="@Model.Password" type="password" placeholder="Password" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline" />
                </div>

                <div class="flex flex-col pt-4">
                    <label for="confirm-password" class="text-lg">Confirm Password</label>
                    <input asp-for="@Model.ConfirmPassword" type="password" placeholder="Password" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline" />
                </div>

                <input type="submit" value="Register" class="bg-black text-white font-bold text-lg hover:bg-gray-700 p-2 mt-8" />
            </form>
            <div class="text-center pt-12 pb-12">
                <p>Already have an account? <a href="/" class="underline font-semibold">Log in here.</a></p>
            </div>
        </div>

    </div>

    <!-- Image Section -->
    <div class="w-1/2 shadow-2xl">
        <img class="object-cover w-full h-screen hidden md:block" src="https://source.unsplash.com/IXUM4cJynP0" alt="Background" />
    </div>
</div>