CoreBridge/Models/DTO/Pagenation.cs
using Google.Api;
using Newtonsoft.Json;

namespace CodeBridge.Models.DTO
{
    public class Pagenation
    {
        [JsonProperty("count")]
        public int Count { get; set; }

        public PageDto? PageDto { get; set; }

        public string Controller { get; set; }
        public string Action { get; set; }

        public Pagenation(PageDto page, int count)
        {
            Count = count;
            PageDto = page;
        }
        public int pageCount 
        { 
            get {
                int ret = 0;
                if (PageDto != null)
                    ret = (int)Math.Ceiling((float)Count / PageDto.PageSize);
                
                return ret;
            } 
        }
        public int currentPage
        {
            get
            {
                int ret = 0;
                if (PageDto != null)
                    ret = PageDto.StartPage;

                return ret;
            }
        }
        public int leftMostPage
        {
            get
            {
                int ret = 5;
                if (PageDto != null && PageDto.StartPage > ret)
                {
                    ret = PageDto.StartPage-ret;
                    
                }
                else
                {
                    ret = 0;
                }

                return ret;
            }
        }

        public int pageRange 
        {
            get
            {
                int ret = 5;

                if (PageDto != null && pageCount > PageDto.StartPage)
                {
                    ret = PageDto.StartPage + ret;

                }
                else
                {
                    ret = pageCount;
                }

                return ret;
            }
        }
    }
}

CoreBridge/Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CoreBridge.Models.Context;
using CoreBridge.Models.Entity;
using CoreBridge.Models.Interfaces;
using CoreBridge.Services.Interfaces;
using CoreBridge.Models.DTO;
using CoreBridge.Services;
using AutoMapper;
using Microsoft.AspNetCore.Identity;

using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.AspNetCore.Authentication;
using System.Text;
using System.Text.Encodings.Web;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using CoreBridge.Models;
using CoreBridge.Attributes;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using XAct.Users;

namespace CoreBridge.Controllers
{
    /// <summary>
    /// スーパーユーザー向け画面コントローラー
    /// ゲーム制作ユーザーの初期登録、ゲーム制作ユーザーアカウントの一覧表示等を制御
    /// </summary>
    [AuthorizeRoles(AdminUserRoleEnum.AdminUser)]
    public class AccountsController : Controller
    {
        private readonly IAppUserService _appUserService;
        private readonly ITitleInfoService _titleInfoService;
        private readonly IMapper _mapper;
        private readonly ILogger<AccountsController> _logger;

        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        [ViewData]
        public string IsDeleteTab { get; set; } = "";

        public bool IsDeleteView { get; set; } = false;

        public AccountsController(IAppUserService appUserService, ITitleInfoService titleInfoService,
            SignInManager<IdentityUser> signInManager,UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager, ILogger<AccountsController> logger)
        {
            _appUserService = appUserService;
            _titleInfoService = titleInfoService;
            _signInManager = signInManager;
            _userManager = userManager;
            _roleManager = roleManager;

            var mapConfig = new MapperConfiguration(cfg => cfg.CreateMap<AppUserDto, AppUser>());
            _mapper = new Mapper(mapConfig);
            _logger = logger;
        }

        // GET: Accounts        
        public async Task<IActionResult> Index(bool IsDeleteView = false)
        {
            if (IsDeleteView)
            {
                //すべて表示する
                ViewData["IsDeleteTab"] = "checked";
                return View(await _appUserService.FindAsync());
            }

            ViewData["IsDeleteTab"] = "";
            var getInfo = await _appUserService.FindAsync();
            var viewInfo = getInfo.Where(d => d.IsDelete == false);
            return View(viewInfo);
        }

        // GET: Accounts/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _appUserService == null)
            {
                return NotFound();
            }

            var appUser = await _appUserService.GetByUserIdAsync(id);
            if (appUser == null)
            {
                return NotFound();
            }

            return View(appUser);
        }

        public async Task<IActionResult> UserList()
        {
            return View(await _appUserService.FindAsync());
        }

        // GET: Accounts/Create
        public async Task<IActionResult> Create()
        {
            return LocalRedirect("/AppUserRegister");
        }

        // POST: Accounts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserId,TitleCode,Password")] AppUserDto appUser)
        {
            if (ModelState.IsValid)
            {
                //タイトルコードの確認をする
                if (appUser.TitleCode != null)
                {
                    var check = await _titleInfoService.FindTitleCode(appUser.TitleCode);
                    if (check == false)
                    {
                        string errorMsg = "同一のタイトルコードがあませんでした！登録済みタイトルコードを利用してください。";
                        ViewBag.Alert = errorMsg;
                        ModelState.AddModelError(string.Empty, errorMsg);
                        return View();
                    }
                }

                //登録する
                await _appUserService.GenerateAppUser(appUser);
                return View();
            }
            return View(appUser);
        }



        // GET: Accounts/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _appUserService == null)
            {
                return NotFound();
            }

            var appUser = await _appUserService.GetByUserIdAsync(id);
            if (appUser == null)
            {
                return NotFound();
            }

            appUser.Password = String.Empty;

            return View(appUser);
        }

        // POST: Accounts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("UserId,TitleCode,Role,Email,Password")] AppUserDto appUser)
        {
            if (ModelState.IsValid)
            {
                //エラーチェック
                ViewBag.Alert = null;
                var check = await _titleInfoService.FindTitleCode(appUser.TitleCode);
                if (check == false)
                {
                    string errorMsg = "同一のタイトルコードがあませんでした！登録済みタイトルコードを利用してください。";
                    ViewBag.Alert = errorMsg;
                    ModelState.AddModelError(string.Empty, errorMsg);
                    return View(appUser);
                }

                try
                {
                    //DBに保存されている情報を取得
                    var info = await _appUserService.GetByUserIdAsync(appUser.UserId);
                    if(info == null) 
                    {
                        return View(appUser); 
                    }

                    //EmailからUserインスタンス取得
                    var user = await _userManager.FindByEmailAsync(info.Email);

                    //Emailの変更確認.
                    if (info.Email != appUser.Email)
                    {
                        //トークン生成
                        var email_token = await _userManager.GenerateChangeEmailTokenAsync(user, appUser.Email);

                        //ユーザーのEmail情報を更新
                        await _userManager.ChangeEmailAsync(user, appUser.Email, email_token);
                    }

                    //サインイン情報のアップデート
                    if (appUser.Password != null)
                    {
                        //UserManagerのパスワード更新
                        var token = await _userManager.GeneratePasswordResetTokenAsync(user);
                        var ret = await _userManager.ResetPasswordAsync(user, token, appUser.Password);

                        //パスワードをハッシュ化
                        var new_passwordHash = _userManager.PasswordHasher.HashPassword(user, appUser.Password);
                        appUser.Password = new_passwordHash;
                    }

                    //ロール管理アップデート.
                    var roleName = appUser.Role.ToString();
                    await _roleManager.CreateAsync(new IdentityRole(roleName));
                    await _userManager.AddToRoleAsync(user, roleName);

                    //DB更新
                    await _appUserService.UpdateAsync(appUser);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AppUserExists(appUser.UserId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            return View(appUser);
        }

        // GET: Accounts/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _appUserService == null)
            {
                return NotFound();
            }

            var appUser = await _appUserService.GetByUserIdAsync(id);
            if (appUser == null)
            {
                return NotFound();
            }

            return View(appUser);
        }

        // POST: Accounts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_appUserService == null)
            {
                return Problem("Entity set 'CoreBridgeContext.AppUsers'  is null.");
            }

            var appUser = await _appUserService.GetByUserIdAsync(id);
            if (appUser != null)
            {
                //削除フラグをON！
                appUser.IsDelete = true;

                //DB更新
                await _appUserService.UpdateAsync(appUser);

                /* Spannerの場合リレーショナルを組んでいると削除がロジックでやろうとすると難航する可能性あり
                 * 今回は下記の処理は行わず、削除フラグにて表示を切り替えるようにする
                 * 削除する必要がある場合は、運用でカバーする流れにする（ 12/26 根本さんと相談済み：野竹）

                //EmailからUserインスタンス取得

CoreBridge/Controllers/AppUserLoginController.cs
using CoreBridge.Models.DTO;
using CoreBridge.Services.Interfaces;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CoreBridge.Controllers
{
    public class AppUserLoginController : Controller
    {
        private readonly IAppUserService _appUserSerice;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IUserStore<IdentityUser> _userStore;
        private readonly ILogger<UserLoginController> _logger;

        public AppUserLoginController(IAppUserService appUserSerice, SignInManager<IdentityUser> signInManager, 
            UserManager<IdentityUser> userManager, IUserStore<IdentityUser> userStore, ILogger<UserLoginController> logger)
        {
            _appUserSerice = appUserSerice;
            _signInManager = signInManager;
            _userManager = userManager;
            _userStore = userStore;
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateAsync(AppUserDto dto)
        {
            var info = await _appUserSerice.GetByUserIdAsync(dto.UserId);
            //UserID確認
            if(info == null)
            {
                ModelState.AddModelError(string.Empty, "正しいUserIDを指定してください。");
                return View(dto);
            }

            //タイトルコード確認
            if (dto.TitleCode != info.TitleCode)
            {
                ModelState.AddModelError(string.Empty, "タイトルコードが不正です。");
                return View(dto);
            }

            string returnUrl = Url.Content("~/");
            if (ModelState.IsValid)
            {
                //サインイン処理
                var result = await _signInManager.PasswordSignInAsync(dto.UserId, dto.Password, false, lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    _logger.LogInformation("User logged in.");

                    if (dto.TitleCode != null)
                    {
                        CookieOptions cookieOptions = new CookieOptions();
                        cookieOptions.Secure = true;
                        cookieOptions.Expires = DateTime.UtcNow.AddDays(7);
                        HttpContext.Response.Cookies.Append("TitleCode-Cookie", dto.TitleCode, cookieOptions);
                    }

                    return LocalRedirect($"/AppManagementUser/UserList"); 
                }
                if (result.RequiresTwoFactor) //二段階認証
                {
                    return RedirectToPage("./LoginWith2fa", new { ReturnUrl = returnUrl, RememberMe = false });
                }
                if (result.IsLockedOut) //ログアウト確認
                {
                    _logger.LogWarning("User account locked out.");
                    return RedirectToPage("./Lockout");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "E-Mailまたは、パスワードが不正です");
                    return View(dto);
                }
            }

            return View(dto);
        }
    }
}

CoreBridge/Controllers/LoginController.cs
#nullable disable

using CoreBridge.Models.DTO;
using CoreBridge.Services.Interfaces;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics.Contracts;
using Microsoft.Extensions.Logging;

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace CoreBridge.Controllers
{
    public class LoginController : Controller
    {
        private readonly ILogger<LoginController> _logger;
        private readonly IAdminUserService _adminUserService;

        // サインイン必須
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;

        public LoginController(ILogger<LoginController> logger, IAdminUserService adminUserService, SignInManager<IdentityUser> signInManager,
            UserManager<IdentityUser> userManager)
        {
            _logger = logger;
            _adminUserService = adminUserService;
            _signInManager = signInManager;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            return RedirectToAction("Home", "Index");
        }

        [HttpPost]
        public async Task<IActionResult> CreateAsync(AdminUserDto dto)
        {
            //サインイン
            string returnUrl = Url.Content("~/");

            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(dto.EMail, dto.Password, false, lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    _logger.LogInformation("User logged in.");
                    return LocalRedirect("/Accounts");
                }
                if (result.RequiresTwoFactor) //二段階認証
                {
                    return RedirectToPage("./LoginWith2fa", new { ReturnUrl = returnUrl, RememberMe = false });
                }
                if (result.IsLockedOut) //ログアウト確認
                {
                    _logger.LogWarning("User account locked out.");
                    return RedirectToPage("./Lockout");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "E-Mailまたは、パスワードが不正です");
                    return View(dto);
                }
            }

            return View(dto);
        }
    }
}

CoreBridge/Views/Shared/_FormError.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
    <div class="p-10 flex flex-col space-y-3">
@{
        foreach (var modelState in ViewData.ModelState.Values)
        {
            foreach (var error in modelState.Errors)
            {
                    <div class="bg-red-100 p-5 w-full">
                        <div class="flex space-x-3">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" class="flex-none fill-current text-red-500 h-4 w-4">
                                <path d="M12 0c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm4.597 17.954l-4.591-4.55-4.555 4.596-1.405-1.405 4.547-4.592-4.593-4.552 1.405-1.405 4.588 4.543 4.545-4.589 1.416 1.403-4.546 4.587 4.592 4.548-1.403 1.416z"></path>
                            </svg>
                        </div>
                        <div class="leading-tight flex flex-col space-y-2">
                        </div>
                        <div class="flex-1 leading-snug text-sm text-red-600">
                            @error.ErrorMessage
                        </div>
                    </div>
            }
         }
    }

        </div>

CoreBridge/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"] - agw_accounting</title>
    <meta name="author" content="David Grzyb">
    <meta name="description" content="">
    <!-- Tailwind -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.2.19/tailwind.min.css" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Karla:400,700&display=swap" rel="stylesheet">
        <style>
        .font-family-karla { font-family: karla; }
        .bg-sidebar { background: #3d68ff; }
        .cta-btn { color: #3d68ff; }
        .upgrade-btn { background: #1947ee; }
        .upgrade-btn:hover { background: #0038fd; }
        .active-nav-link { background: #1947ee; }
        .nav-item:hover { background: #1947ee; }
        .account-link:hover { background: #3d68ff; }
        </style>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/agw_accounting.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body class="bg-gray-100 font-family-karla flex">

    @Html.Partial("_NavigateMenu")

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CoreBridge/Views/Shared/_Login.cshtml
@model CoreBridge.Models.DTO.AdminUserDto

<div class="w-full flex flex-wrap">
     <!-- Login Section -->
     <div class="w-full md:w-1/2 flex flex-col">

        @Html.Partial("_logo")
         <div class="flex flex-col justify-center md:justify-start my-auto pt-8 md:pt-0 px-8 md:px-24 lg:px-32">
             <p class="text-center text-3xl">CoreBridge Login.</p>
             @Html.Partial("_FormError")
            <form class="flex flex-col pt-3 md:pt-8" asp-controller="Login" asp-action="Create" method="post" >
                @Html.AntiForgeryToken()
                 <div class="flex flex-col pt-4">
                     <label for="email" class="text-lg">Email</label>
                     <input asp-for="@Model.EMail" type="email" placeholder="your@email.com" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline">
                 </div>
 
                 <div class="flex flex-col pt-4">
                     <label for="password" class="text-lg">Password</label>
                     <input asp-for="@Model.Password" type="password" placeholder="Password" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline">
                 </div>
                 <input asp-for="@Model.Name" type="hidden" value="aa"/>
                 <input asp-for="@Model.ConfirmPassword" type="hidden" value="aa"/>
  
                 <input type="submit" value="Log In" class="bg-black text-white font-bold text-lg hover:bg-gray-700 p-2 mt-8">
             </form>
             <div class="text-center pt-12 pb-12">
                 <p>Don't have an account? <a href="/UserRegister" class="underline font-semibold">Register here.</a></p>
             </div>
         </div>

     </div>

     <!-- Image Section -->
     <div class="w-1/2 shadow-2xl">
         <img class="object-cover w-full h-screen hidden md:block" src="https://source.unsplash.com/IXUM4cJynP0">
     </div>
</div>

CoreBridge/Views/Shared/_LoginAdminUser.cshtml
@model CoreBridge.Models.DTO.AppUserDto

<div class="w-full flex flex-wrap">
    <!-- Login Section -->
    <div class="w-full md:w-1/2 flex flex-col">

        @Html.Partial("_logo")
        <div class="flex flex-col justify-center md:justify-start my-auto pt-8 md:pt-0 px-8 md:px-24 lg:px-32">
            <p class="text-center text-3xl">Admin User Login</p>
            @Html.Partial("_FormError")
            <form class="flex flex-col pt-3 md:pt-8" asp-controller="AppUserLogin" asp-action="Create" method="post">
                @Html.AntiForgeryToken()
                <div class="flex flex-col pt-4">
                    <label for="User ID" class="text-lg">UserID</label>
                    <input asp-for="@Model.UserId" type="text" placeholder="UserID" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline">
                </div>
                <div class="flex flex-col pt-4">
                    <label for="Title Code" class="text-lg">TitleCode</label>
                    <input asp-for="@Model.TitleCode" type="text" placeholder="TitleCode" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline">
                </div>
                <div class="flex flex-col pt-4">
                    <label for="password" class="text-lg">Password</label>
                    <input asp-for="@Model.Password" type="password" placeholder="Password" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline">
                </div>
                @*<input asp-for="@Model.Name" type="hidden" value="aa"/>*@
                <input asp-for="@Model.ConfirmPassword" type="hidden" value="aa" />

                <input type="submit" value="Log In" class="bg-black text-white font-bold text-lg hover:bg-gray-700 p-2 mt-8">
            </form>
            <div class="text-center pt-12 pb-12">
                <p>Don't have an account? <a href="/AppUserRegister" class="underline font-semibold">Register here.</a></p>
            </div>
        </div>

    </div>

    <!-- Image Section -->
    <div class="w-1/2 shadow-2xl">
        <img class="object-cover w-full h-screen hidden md:block" src="https://source.unsplash.com/IXUM4cJynP0">
    </div>
</div>

CoreBridge/Views/Shared/_LoginUser.cshtml
@model CoreBridge.Models.DTO.AppUserDto

<div class="w-full flex flex-wrap">
     <!-- Login Section -->
     <div class="w-full md:w-1/2 flex flex-col">

        @Html.Partial("_logo")
         <div class="flex flex-col justify-center md:justify-start my-auto pt-8 md:pt-0 px-8 md:px-24 lg:px-32">
             <p class="text-center text-3xl">Admin User Login</p>
             @Html.Partial("_FormError")
            <form class="flex flex-col pt-3 md:pt-8" asp-controller="AppUserLogin" asp-action="Create" method="post">
                @Html.AntiForgeryToken()
                 <div class="flex flex-col pt-4">
                     <label for="User ID" class="text-lg">UserID</label>
                     <input asp-for="@Model.UserId" type="text" placeholder="UserID" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline">
                 </div>
                 <div class="flex flex-col pt-4">
                     <label for="Title Code" class="text-lg">TitleCode</label>
                    <input asp-for="@Model.TitleCode" type="text" placeholder="TitleCode" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline">
                 </div> 
                 <div class="flex flex-col pt-4">
                     <label for="password" class="text-lg">Password</label>
                     <input asp-for="@Model.Password" type="password" placeholder="Password" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline">
                 </div>
  
                 <input type="submit" value="Log In" class="bg-black text-white font-bold text-lg hover:bg-gray-700 p-2 mt-8">
             </form>
         </div>

     </div>

     <!-- Image Section -->
     <div class="w-1/2 shadow-2xl">
         <img class="object-cover w-full h-screen hidden md:block" src="https://source.unsplash.com/IXUM4cJynP0">
     </div>
</div>

CoreBridge/Views/Shared/_Logo.cshtml
@{
}
         <div class="flex justify-center md:justify-start pt-12 md:pl-12 md:-mb-24">
             <a href="/" class="bg-black text-white font-bold text-xl p-4">Logo</a>
         </div>

CoreBridge/Views/Shared/_NavigateMenu.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@inject NavigationManager NavigationManager
@{
}
    <aside class="relative bg-sidebar h-screen w-64 hidden sm:block shadow-xl">
        <div class="p-6">
            <a href="index.html" class="text-white text-3xl font-semibold uppercase hover:text-gray-300">Logo</a>
        </div>
        <nav class="text-white text-base font-semibold pt-3">
@*            <a href="/Dashboard" class="flex items-center active-nav-link text-white py-4 pl-6 nav-item">
                <i class="fas fa-tachometer-alt mr-3"></i>
                Dashboard
            </a>*@

            @if(User.IsInRole(AdminUserRoleEnum.AdminUser.ToString()))
            {
                <a href="/Accounts" class="flex items-center active-nav-link text-white py-4 pl-6 nav-item">
                    <i class="fas fa-tachometer-alt mr-3"></i>
                    <p>@Localizer["GameManagementTitle"]</p>
                </a>

                @if (User?.Identity?.IsAuthenticated ?? false)
                {
                    <a asp-controller="Accounts" asp-action="Signout" class="btn">
                        <i class="fas fa-tachometer-alt mr-3"></i>
                        <p>@Localizer["LogOut"]</p>
                    </a>
                }
            }
            @if(!User.IsInRole(AdminUserRoleEnum.AdminUser.ToString()))
            {
                <a href="/AppManagementUser/UserList" class="flex items-center active-nav-link text-white py-4 pl-6 nav-item">
                    <i class="fas fa-tachometer-alt mr-3"></i>
                    <p>@Localizer["ManagementTitle"]</p>
                </a>
                <a href="/AppManagementUser" class="flex items-center active-nav-link text-white py-4 pl-6 nav-item">
                    <i class="fas fa-tachometer-alt mr-3"></i>
                    <p>@Localizer["KPITitle"]</p>
                </a>
                <a href="/AppManagementUser" class="flex items-center active-nav-link text-white py-4 pl-6 nav-item">
                    <i class="fas fa-tachometer-alt mr-3"></i>
                    <p>@Localizer["UserInfoTitle"]</p>
                </a>
                <a href="/AppManagementUser" class="flex items-center active-nav-link text-white py-4 pl-6 nav-item">
                    <i class="fas fa-tachometer-alt mr-3"></i>
                    <p>@Localizer["NgWordTitle"]</p>
                </a>
                <a href="/AppManagementUser" class="flex items-center active-nav-link text-white py-4 pl-6 nav-item">
                    <i class="fas fa-tachometer-alt mr-3"></i>
                    <p>@Localizer["RewardTitle"]</p>
                </a>
                <a href="/AppManagementUser" class="flex items-center active-nav-link text-white py-4 pl-6 nav-item">
                    <i class="fas fa-tachometer-alt mr-3"></i>
                    <p>@Localizer["PurchaseTitle"]</p>
                </a>

                @if (User?.Identity?.IsAuthenticated ?? false)
                {
                    <a asp-controller="AppManagementUser" asp-action="Signout" class="btn">
                        <i class="fas fa-tachometer-alt mr-3"></i>
                        <p>@Localizer["LogOut"]</p>
                    </a>
                }
            }

@*            <a href="/hangfire" class="flex items-center text-white opacity-75 hover:opacity-100 py-4 pl-6 nav-item">
                <i class="fas fa-calendar mr-3"></i>
                Job Scheduler
            </a>*@
        </nav>
    </aside>