CoreBridge/Controllers/AppManagementUserController.cs
using Microsoft.AspNetCore.Mvc;
using CoreBridge.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
//using System.Web.Mvc;
using Microsoft.AspNetCore.Mvc;
using CoreBridge.Models.DTO;
using CoreBridge.Services.Interfaces;
using CoreBridge.ViewModels;
using CoreBridge.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Localization;
using CoreBridge.Attributes;
using CoreBridge.Models;
using CoreBridge.Models.lib;
using System.Text.RegularExpressions;
using XAct;
using System.Collections;

namespace CoreBridge.Controllers
{
    //[Route("{titleCode}/[controller]/[action]")]
    public class AppManagementUserController : Controller
    {
        private readonly IAppUserService _appUserService;
        private readonly ITitleInfoService _titleInfoService;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IUserStore<IdentityUser> _userStore;
        private readonly ILogger<UserLoginController> _logger;
        private readonly IStringLocalizer<SharedResource> _localizer;
        private readonly RoleManager<IdentityRole> _roleManager;

        //リセット用
        public bool IsReset { get; set; } = false;

        public AppManagementUserController(IAppUserService appUserService, ITitleInfoService titleInfoService, SignInManager<IdentityUser> signInManager, 
            UserManager<IdentityUser> userManager, IUserStore<IdentityUser> userStore, IStringLocalizer<SharedResource> stringLocalizer, RoleManager<IdentityRole> roleManager)
        {
            _appUserService = appUserService;
            _titleInfoService = titleInfoService;
            _signInManager = signInManager;
            _userManager = userManager;
            _userStore = userStore;
            _localizer = stringLocalizer;
            _roleManager = roleManager;
        }

        //[Area("AppManagementUser")]
        //[ActionName("top")]
        public async Task<IActionResult> Index(string? titleCode)
        {
            return View();
        }

        [AuthorizeRoles(AdminUserRoleEnum.AdminUser, AdminUserRoleEnum.BneManager, AdminUserRoleEnum.Manager,
            AdminUserRoleEnum.Reference, AdminUserRoleEnum.EditReference)]
        public async Task<IActionResult> UserList(string Title, AppUserSearchDto appUserSearchDto, string Search, string Clear, MUserIndexViewModel mUserVM)
        {
            //それぞれのデータを読み込み
            bool loginFrst = false;
            if (HttpContext.Request.Cookies.TryGetValue("TitleCode-Cookie", out var value))
            {
                Title = value;
                HttpContext.Response.Cookies.Delete("TitleCode-Cookie");
            }

            var appUserDto = new AppUserDto();
            UserOperation userOperation = new UserOperation(_appUserService);
            appUserDto.UserId = await userOperation.CreateUserId();
            appUserDto.TitleCode = Title;

            var appUserDtos = await _appUserService.ListAsync();
            //List<AppUserDto> userList = new List<AppUserDto>();
            List<AppUserDto> userList = appUserDtos.Where(d => d.IsDelete == false).ToList(); //基本的に削除されてものは表示されなくていいはず（運用でカバーするということなので）

            if (Search != null)
            {
                //検索SQL
                if(appUserSearchDto.UserId != null)
                {
                    userList = userList.Where(x => x.UserId == appUserSearchDto.UserId).ToList();
                }

                if (mUserVM.RoleSearchIndex > 0)
                {
                    userList = userList.Where(x => x.Role == (AdminUserRoleEnum)mUserVM.RoleSearchIndex).ToList();
                }

                if (appUserSearchDto.TitleCode != null)
                {
                    userList = userList.Where(x => x.TitleCode == appUserSearchDto.TitleCode).ToList();
                }

                if (appUserSearchDto.CreatedDate != null && appUserSearchDto.UpdatedDate != null)
                {
                    userList = userList.Where(x => x.CreatedAt >= appUserSearchDto.CreatedDate)
                        .Where(x => x.UpdatedAt <= appUserSearchDto.UpdatedDate).ToList();
                }
            }

            var mUserIndexVM = new MUserIndexViewModel
            {
                AppUserDto = appUserDto,
                AppUserDtos = userList                
            };

            return View(mUserIndexVM);
        }

        private IdentityUser CreateUser()
        {
            try
            {
                return Activator.CreateInstance<IdentityUser>();
            }
            catch
            {
                throw new InvalidOperationException($"Can't create an instance of '{nameof(IdentityUser)}'. " +
                    $"Ensure that '{nameof(IdentityUser)}' is not an abstract class and has a parameterless constructor, or alternatively " +
                    $"override the register page in /Areas/Identity/Pages/Account/Register.cshtml");
            }
        }

        // GET: Accounts/Edit/5
        public async Task<IActionResult> Edit(string id, MUserIndexViewModel mUserIndexViewModel)
        {
            if (id == null || _appUserService == null)
            {
                return NotFound();
            }

            var appUser = await _appUserService.GetByUserIdAsync(id);
            if (appUser == null)
            {
                return NotFound();
            }

            //ロール情報を設定
            appUser.Role = (AdminUserRoleEnum)mUserIndexViewModel.RoleIndex;

            return View(appUser);
        }

        // POST: Accounts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("UserId,TitleCode,Role,Email,Password")] AppUserDto appUser)
        {
            if (ModelState.IsValid)
            {
                //エラーチェック
                ViewBag.Alert = null;
                var check = await _titleInfoService.FindTitleCode(appUser.TitleCode);
                if (check == false)
                {
                    string errorMsg = "同一のタイトルコードがあませんでした！登録済みタイトルコードを利用してください。";
                    ViewBag.Alert = errorMsg;
                    ModelState.AddModelError(string.Empty, errorMsg);
                    return View(appUser);
                }

                try
                {
                    //DBに保存されている情報を取得
                    var info = await _appUserService.GetByUserIdAsync(appUser.UserId);
                    if (info == null)
                    {
                        return View(appUser);
                    }

                    //EmailからUserインスタンス取得
                    var user = await _userManager.FindByEmailAsync(info.Email);

                    //Emailの変更確認.
                    if (info.Email != appUser.Email)
                    {
                        //トークン生成
                        var email_token = await _userManager.GenerateChangeEmailTokenAsync(user, appUser.Email);

                        //ユーザーのEmail情報を更新
                        await _userManager.ChangeEmailAsync(user, appUser.Email, email_token);
                    }

                    //サインイン情報のアップデート
                    if (appUser.Password != null)
                    {
                        //UserManagerのパスワード更新
                        var token = await _userManager.GeneratePasswordResetTokenAsync(user);
                        var ret = await _userManager.ResetPasswordAsync(user, token, appUser.Password);

                        //パスワードをハッシュ化
                        var new_passwordHash = _userManager.PasswordHasher.HashPassword(user, appUser.Password);
                        appUser.Password = new_passwordHash;
                    }

                    //ロール管理アップデート.
                    var roleName = appUser.Role.ToString();
                    await _roleManager.CreateAsync(new IdentityRole(roleName));
                    await _userManager.AddToRoleAsync(user, roleName);

                    //DB更新
                    await _appUserService.UpdateAsync(appUser);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AppUserExists(appUser.UserId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction("UserList");
            }

            return View(appUser);
        }

        [HttpPost]
        public async Task<IActionResult> Confirm(MUserIndexViewModel dto)
        {
            ViewBag.Alert = null;
            //ModelState.Clear();

            //タイトルコードの存在は確認する.
            if (dto.AppUserDto.TitleCode != null)
            {
                //タイトルコードの存在は確認する.
                var check = await _titleInfoService.FindTitleCode(dto.AppUserDto.TitleCode);
                if (check == false)
                {
                    string errorMsg = "同一のタイトルコードがあませんでした！登録済みタイトルコードを利用してください。";
                    ViewBag.Alert = errorMsg;
                    ModelState.AddModelError(string.Empty, errorMsg);
                }
            }

            //パスワードの手動でのバリテーション
            if (dto.AppUserDto.Password != null)
            {
                var hasNumber = new Regex(@"[0-9]+");
                var hasUpperChar = new Regex(@"[A-Z]+");

CoreBridge/Views/AppManagementUser/Confirm.cshtml
@model CoreBridge.ViewModels.MUserIndexViewModel
@{
    Layout = "_TopLayout";
}
<div class="w-full flex flex-wrap">
    <!-- Register Section -->
    <div class="w-full md:w-1/2 flex flex-col">

        @Html.Partial("_logo")

        <div class="flex flex-col justify-center md:justify-start my-auto pt-8 md:pt-0 px-8 md:px-24 lg:px-32">
            <p class="text-center text-3xl">以下の内容で登録をしますか？</p>
            @Html.Partial("_FormError")
            <form class="flex flex-col pt-3 md:pt-8" asp-controller="AppManagementUser" asp-action="Create" method="post">
                @Html.AntiForgeryToken()
                <div class="flex flex-col pt-4">
                    <label for="userid" class="text-lg">User ID</label>
                    @Model.AppUserDto.UserId
                    <input asp-for="@Model.AppUserDto.UserId" type="hidden" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline" />
                </div>

                <div class="flex flex-col pt-4">
                    <label for="titel code" class="text-lg">Title Code</label>
                    @Model.AppUserDto.TitleCode
                    <input asp-for="@Model.AppUserDto.TitleCode" type="hidden" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline" />
                </div>

                <div class="flex flex-col pt-4">
                    <label for="titel code" class="text-lg">Role</label>
                    @*@Model.AppUserDto.Role*@
                    @if (Model.AppUserDto.Role == AdminUserRoleEnum.Manager)
                    {
                        ViewData["massage"] = "-1：DataLake権限";
                    }
                    @if (Model.AppUserDto.Role == AdminUserRoleEnum.Reference)
                    {
                        ViewData["massage"] = "1：参照権限";
                    }
                    @if (Model.AppUserDto.Role == AdminUserRoleEnum.EditReference)
                    {
                        ViewData["massage"] = "2：参照権限＋編集権限";
                    }
                    @ViewData["massage"]
                    <input asp-for="@Model.AppUserDto.Role" type="hidden" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline" />
                </div>

                <div class="flex flex-col pt-4">
                    <label for="titel code" class="text-lg">Email</label>
                    @Model.AppUserDto.Email
                    <input asp-for="@Model.AppUserDto.Email" type="hidden" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline" />
                </div>

                <div class="flex flex-col pt-4">
                    <label for="password" class="text-lg">Password</label>
                    @Model.AppUserDto.Password
                    <input asp-for="@Model.AppUserDto.Password" type="hidden" placeholder="Password" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline" />
                </div>

                <div class="flex flex-col pt-4">
                    <label for="confirm-password" class="text-lg">Confirm Password</label>
                    @Model.AppUserDto.ConfirmPassword
                    <input asp-for="@Model.AppUserDto.ConfirmPassword" type="hidden" placeholder="Password" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline" />
                </div>
                @if (ViewBag.Alert == null)
                {
                    <input type="submit" value="Register" class="bg-black text-white font-bold text-lg hover:bg-gray-700 p-2 mt-8" />
                }
            </form>
            <div class="text-center pt-12 pb-12">
                <div>
                    <a asp-action="UserList">前の画面に戻る</a>
                </div>
            </div>
        </div>

    </div>

    <!-- Image Section -->
    <div class="w-1/2 shadow-2xl">
        <img class="object-cover w-full h-screen hidden md:block" src="https://source.unsplash.com/IXUM4cJynP0" alt="Background" />
    </div>
</div>
<script>
    var alert_del = document.querySelectorAll('.alert-del');
    alert_del.forEach((x) =>
        x.addEventListener('click', function () {
            x.parentElement.classList.add('hidden');
        })
    );
</script>

CoreBridge/Views/AppManagementUser/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_TopLayout";
}
<div class="w-full flex flex-wrap">
    <!-- Register Section -->
    <div class="w-full md:w-1/2 flex flex-col">

        @*@Html.Partial("_logo")*@
        @Html.Partial("_FormError")
        @if (ViewBag.Alert == null)
        {
            <div class="flex flex-col justify-center md:justify-start my-auto pt-8 md:pt-0 px-8 md:px-24 lg:px-32">
                <p class="text-center text-3xl">登録完了</p>
            </div>
        }
        else
        {
            <div class="flex flex-col justify-center md:justify-start my-auto pt-8 md:pt-0 px-8 md:px-24 lg:px-32">
                <p class="text-center text-3xl">登録が失敗しました</p>
            </div>
        }

        <p>一覧は<a href="/AppManagementUser/UserList" class="underline font-semibold">こちら</a>から！</p>
    </div>
</div>

CoreBridge/Views/AppManagementUser/Delete.cshtml
@*@model CoreBridge.Models.Entity.AppUser*@
@model CoreBridge.Models.DTO.AppUserDto

@{
    ViewData["Title"] = "Delete";
}

<h1>ユーザー情報削除画面</h1>

<h3>下記のユーザー情報を削除しますか？</h3>
<div>
    <h4>AppUser</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TitleCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TitleCode)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Role)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Role)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @*@Html.DisplayFor(model => model.Password)*@
            <input type="password" value="@Html.DisplayFor(model => model.Password)"/>
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="UserId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="UserList">前の画面に戻る</a>
    </form>
</div>

CoreBridge/Views/AppManagementUser/Details.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

COSMOSの詳細画面をここに作る！

CoreBridge/Views/AppManagementUser/Edit.cshtml
@*@model CoreBridge.Models.Entity.AppUser*@
@model CoreBridge.Models.DTO.AppUserDto

@{
    ViewData["Title"] = "Edit";
}

<h1>ユーザー情報編集</h1>

<h4>AppUser</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        @*@Html.Partial("_FormError")*@
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <input asp-for="UserId" class="form-control" readonly />
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TitleCode" class="control-label"></label>
                <input asp-for="TitleCode" class="form-control" />
                <span asp-validation-for="TitleCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Role" class="control-label"></label>
                <select asp-for="Role" class="form-control" asp-items="Html.GetEnumSelectList<ManagementRoleEnum>()"></select>
                 @*<select asp-for="Role" class="form-control" asp-items="Html.GetEnumSelectList<AdminUserRoleEnum>()"></select>*@
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <span style="color:red;"> ※変更必要な場合のみ入力</span>
                <input type="password" asp-for="Password" class="form-control" />
            </div>
            <input type="hidden" asp-for="UserId" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="UserList">前の画面に戻る</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

CoreBridge/Views/AppManagementUser/Index.cshtml
@model CoreBridge.Models.DTO.AppUserDto
@{
    Layout = "_TopLayout";
}
@Html.Partial("_LoginUser", @Model)

CoreBridge/Views/AppManagementUser/UserList.cshtml
@model CoreBridge.ViewModels.MUserIndexViewModel
@{
    ViewData["Title"] = "User Manager";
}
@if (!User.IsInRole(AdminUserRoleEnum.Reference.ToString())){
<div class="w-full flex flex-wrap">
    <div class="flex flex-col justify-center md:justify-start my-auto pt-8 md:pt-0 px-8">
        @*@Html.Partial("_FormError")*@

        <p class="text-center text-3xl">管理ユーザー登録</p>
        <form class="flex flex-col pt-3 p-2 bg-light border" asp-controller="AppManagementUser" asp-action="Confirm" method="post">
            @Html.AntiForgeryToken()
            <div class="flex flex-col pt-4">
                <label for="name" class="text-lg">User ID</label>
                <input asp-for="@Model.AppUserDto.UserId" type="text" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline" readonly/>
            </div>

            <div class="flex flex-col pt-4">
                <label for="Role" class="text-lg">Role</label>
                <select asp-for="@Model.RoleIndex"
                        asp-items="Html.GetEnumSelectList<CoreBridge.ViewModels.MUserIndexViewModel.RoleEnum>()" class="form-control">
                </select>
            </div>
            <div class="flex flex-col pt-4">
                <label for="title Code" class="text-lg">Title Code</label>
                <input asp-for="@Model.AppUserDto.TitleCode" type="text" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline" />
            </div>
            <div class="flex flex-col pt-4">
                <label for="email" class="text-lg">Email</label>
                <input asp-for="@Model.AppUserDto.Email" type="text" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline" />
            </div>
            <div class="flex flex-col pt-4">
                <label for="password" class="text-lg">Password</label>
                <input asp-for="@Model.AppUserDto.Password" type="password" placeholder="Password" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline" />
            </div>
            <div class="flex flex-col pt-4">
                <label for="confirm-password" class="text-lg">Confirm Password</label>
                <input asp-for="@Model.AppUserDto.ConfirmPassword" type="password" placeholder="Password" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline" />
            </div>
            <input type="submit" value="Register" class="bg-black text-white font-bold text-lg hover:bg-gray-700 p-2 mt-8" />
        </form>

    </div>
</div>
}

<!-- ユーザー検索 -->
<p class="text-3xl ms-3 p-2">検索</p>
<form class="flex flex-col pt-3 p-2 bg-light border w-50" asp-controller="AppManagementUser" asp-action="UserList">
    <p>
        ユーザーID: <input class="border" type="text" asp-for="@Model.AppUserSearchDto.UserId" />
    </p>
    <p>
        ユーザー権限: 
        <select asp-for="@Model.RoleSearchIndex"
                asp-items="Html.GetEnumSelectList<CoreBridge.ViewModels.MUserIndexViewModel.RoleSearchEnum>()"
                class="form-control">
        </select>
    </p>
    <p>
        タイトルコード: <input class="border" type="text" asp-for="@Model.AppUserSearchDto.TitleCode" />
    </p>
    <p>
        作成機関: <input class="border" type="date" asp-for="@Model.AppUserSearchDto.CreatedDate" />～<input class="border" type="date" asp-for="@Model.AppUserSearchDto.UpdatedDate" />
    </p>
    <div style="display: flex; justify-content: center;">
        <input name="Search" class="w-50" type="submit" value="検索" />
        <input name="Clear" class="w-50 ms-2" type="submit" value="リセット" />
    </div>
</form>

<!-- ユーザー一覧 -->
<p class="text-3xl ms-3 p-2">ユーザー一覧</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AppUserDto.UserId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AppUserDto.Role)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AppUserDto.TitleCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AppUserDto.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AppUserDto.Password)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AppUserDto.CreatedAt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AppUserDto.UpdatedAt)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.AppUserDtos)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.UserId)
                </td>
                <td>
                    @*@Html.DisplayFor(modelItem => item.Role)*@
                    @if(item.Role == AdminUserRoleEnum.Manager){
                        ViewData["massage"] = "-1：DataLake権限";
                    }
                    @if (item.Role == AdminUserRoleEnum.Reference)
                    {
                        ViewData["massage"] = "1：参照権限";
                    }
                    @if (item.Role == AdminUserRoleEnum.EditReference)
                    {
                        ViewData["massage"] = "2：参照権限＋編集権限";
                    }
                    @ViewData["massage"]
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TitleCode)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                    </td>
                <td >
                    <input type="password" size="8" value="@Html.DisplayFor(modelItem => item.Password)" />
                </td>
                <td>
                    <span>
                        @Html.DisplayFor(modelItem => item.CreatedAt)
                    </span>
                </td>
                <td>
                    <span>
                        @Html.DisplayFor(modelItem => item.UpdatedAt)
                    </span>
                </td>

                <td>
                    @if (!User.IsInRole(AdminUserRoleEnum.Reference.ToString()))
                    {
                        <a asp-action="Edit" asp-route-id="@item.UserId">編集</a> 
                        <span>|</span>
                        <a asp-action="Delete" asp-route-id="@item.UserId">削除</a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>